name: Deploy to VPS

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H 89.33.236.171 >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh root@89.33.236.171 << 'EOF'
          cd /var/www/datesantiere
          git pull
          dotnet publish -c Release -o /var/www/datesantiere/publish
          systemctl restart datesantiere
          EOF
